<a href="https://colab.research.google.com/github/anna-lyu/nlp-in-practice/blob/master/Perron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Spanish Soccer Teams

In [ ]:
import numpy as np
from scipy.linalg import eig, eigh
from scipy.sparse.linalg import eigs, eigsh
X = np.matrix([[0.0, 1.0, 1.0, 0.0, 1.0], [0.0, 0.0, 0.0, 0.0, 1.0], [0.0, 1.0, 0.0, 1.0, 0.0], [1.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 1.0, 0.0]])
evals_large, evecs_large = eigsh(X, which='LM')
values, vectors = eig(X)
results = vectors[:,0]
norm_results = results/norm(results, 1)
print(norm_results)

[0.27692153+0.j 0.11620829+0.j 0.17938946+0.j 0.21374036+0.j
 0.21374036+0.j]


##NCAA results - ranking the Big Ten

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving ncaa_data_2017.json to ncaa_data_2017 (1).json


In [ ]:
import json
with open('ncaa_data_2017.json', 'r') as infile:
    ncaa_info_dict = json.load(infile)
ncaa_info_dict['princeton']

[{'opponent': 'byu', 'result': 'L', 'score': [73, 82]},
 {'opponent': 'lehigh', 'result': 'L', 'score': [67, 76]},
 {'opponent': 'lafayette', 'result': 'W', 'score': [71, 55]},
 {'opponent': 'rowan', 'result': 'W', 'score': [46, 108]},
 {'opponent': 'vcu', 'result': 'L', 'score': [70, 81]},
 {'opponent': 'california', 'result': 'L', 'score': [62, 51]},
 {'opponent': 'hawaii', 'result': 'W', 'score': [62, 75]},
 {'opponent': 'liberty', 'result': 'W', 'score': [67, 64]},
 {'opponent': 'saint-josephs', 'result': 'L', 'score': [76, 68]},
 {'opponent': 'monmouth', 'result': 'L', 'score': [90, 96]},
 {'opponent': 'bucknell', 'result': 'W', 'score': [72, 70]},
 {'opponent': 'hampton', 'result': 'W', 'score': [49, 77]},
 {'opponent': 'cal-poly', 'result': 'W', 'score': [52, 81]},
 {'opponent': 'penn', 'result': 'W', 'score': [52, 61]},
 {'opponent': 'brown', 'result': 'W', 'score': [66, 97]},
 {'opponent': 'yale', 'result': 'W', 'score': [58, 66]},
 {'opponent': 'dartmouth', 'result': 'W', 'sc

In [ ]:
big_ten = [
 'purdue',
 'wisconsin',
 'maryland',
 'minnesota',
 'michigan',
 'northwestern',
 'michigan-st',
 'iowa',
 'illinois',
 'ohio-st',
 'indiana',
 'penn-st',
 'nebraska',
 'rutgers'
]
def trimmed(team_key):
    return (team_key,
        [entry for entry in ncaa_info_dict[team_key] if entry['opponent'] in big_ten])
just_big_ten_dict = dict([trimmed(team) for team in big_ten])

In [ ]:
from scipy.sparse import dok_matrix
n = len(big_ten)
M = dok_matrix((n,n))
for i in range(n):
    team = big_ten[i]
    games = just_big_ten_dict[team]
    games = [game for game in games if game['opponent'] in big_ten]
    number_of_games = len(games)
    for game in games:
        opponent = game['opponent']
        win_or_loss = game['result']
        if win_or_loss == "W":
            j = big_ten.index(opponent)
            M[i,j] = M[i,j] + 1 # /number_of_games
                                # Ignore number of games for ease of visualization
print(M.toarray().astype(int))

[[0 1 1 0 0 2 2 1 1 1 2 1 0 1]
 [0 0 1 1 1 1 0 0 1 1 3 1 0 1]
 [0 0 0 1 1 1 1 1 2 2 1 0 0 2]
 [0 0 1 0 0 1 1 0 1 1 1 1 1 1]
 [1 2 0 1 0 0 1 0 2 0 2 1 2 1]
 [0 1 1 0 1 0 0 1 0 1 1 1 2 3]
 [0 1 0 1 1 1 0 1 0 1 0 1 2 1]
 [1 1 1 0 0 0 0 0 0 1 0 1 1 2]
 [0 0 0 0 1 2 1 2 0 1 0 0 1 0]
 [0 1 0 1 1 0 1 0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1 1 1 1 0 1 0 1]
 [0 0 1 1 0 0 1 0 2 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 1 1 0]]


In [ ]:
import numpy as np
from scipy.sparse.linalg import eigs
val,vec = eigs(M, which='LM', k=1)
vec = np.ndarray.flatten(abs(vec))
sorted_indices = vec.argsort()
ranked = [(big_ten[i], vec[i]) for i in sorted_indices]
ranked.reverse()
ranked

[('purdue', 0.38992753243770406),
 ('michigan', 0.3757566665296271),
 ('maryland', 0.337352742736413),
 ('wisconsin', 0.3176005890031199),
 ('northwestern', 0.30187990279927124),
 ('michigan-st', 0.2801978319503931),
 ('illinois', 0.2549724975306111),
 ('minnesota', 0.24809822034435247),
 ('iowa', 0.22085400369895086),
 ('ohio-st', 0.20514389234985997),
 ('indiana', 0.19040557451712828),
 ('penn-st', 0.18185761122877397),
 ('nebraska', 0.16090183127926094),
 ('rutgers', 0.0990154395207426)]